CREATE TABLE `od_items` (
  `items_id` TEXT,
  `items_commonid` TEXT,
  `items_name` TEXT NOT NULL,
  `store_name` TEXT NOT NULL,
  `gc_id` TEXT NOT NULL,
  `gc_id_1` TEXT NOT NULL,
  `brand_id` TEXT NOT NULL,
  `items_costprice` TEXT NOT NULL,
  `items_click` TEXT NOT NULL,
  `items_image` TEXT,
  `items_state` TEXT,
  `items_verify` TEXT,
  `items_addtime` TEXT,
  `items_edittime` TEXT,
  `items_stcids` TEXT,
  `evaluation_good_star` TEXT,
  `is_own_shop` TEXT,
  `goods_custom` TEXT,
  `star_id` TEXT
);
wrangler d1 execute yasyadong --remote --command="CREATE TABLE od_items (
    `items_id` TEXT,
      `items_commonid` TEXT,
      `items_name` TEXT NOT NULL,
      `store_name` TEXT NOT NULL,
      `gc_id` TEXT NOT NULL,
      `gc_id_1` TEXT NOT NULL,
      `brand_id` TEXT NOT NULL,
      `items_costprice` TEXT NOT NULL,
      `items_click` TEXT NOT NULL,
      `items_image` TEXT,
      `items_state` TEXT,
      `items_verify` TEXT,
      `items_addtime` TEXT,
      `items_edittime` TEXT,
      `items_stcids` TEXT,
      `evaluation_good_star` TEXT,
      `is_own_shop` TEXT,
      `goods_custom` TEXT,
      `star_id` TEXT
);"
