name = "yas1104"
main = "src/home.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# D1 数据库配置
[[d1_databases]]
binding = "DB" # 代码中引用数据库的变量名
database_name = "yasyadong" # 数据库名称（与 Cloudflare 仪表板中的一致）
database_id = "171bcdd9-ee81-4fb9-b967-054ff096d273" # 可选，唯一标识数据库

[build]
upload_format = "modules" # 确保 Workers 使用模块化格式
node_compat = true        # 启用 Node.js 兼容模式（必要时）

[[route]]
pattern = "yasyadong1.com/*" # 替换为你的域名
script = "yas1104"          # 匹配的 Workers 脚本名称

[vars]
NODE_ENV = "production" # 可选变量，表示当前运行环境
